AWSTemplateFormatVersion: "2010-09-09"
Resources:
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: "instacart_db"

  OrdersTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: "orders"
        StorageDescriptor:
          Columns:
            - Name: "order_id"
              Type: "int"
            - Name: "user_id"
              Type: "int"
            - Name: "eval_set"
              Type: "string"
            - Name: "order_number"
              Type: "int"
            - Name: "order_dow"
              Type: "int"
            - Name: "order_hour_of_day"
              Type: "int"
            - Name: "days_since_prior"
              Type: "int"
          Location: "s3://your-unique-bucket-name/orders/"
          InputFormat: "org.apache.hadoop.mapred.TextInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
        TableType: "EXTERNAL_TABLE"

  OrderProductsTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: "order_products"
        StorageDescriptor:
          Columns:
            - Name: "order_id"
              Type: "int"
            - Name: "product_id"
              Type: "int"
            - Name: "add_to_cart_order"
              Type: "int"
            - Name: "reordered"
              Type: "int"
          Location: "s3://your-unique-bucket-name/order-products/"
          InputFormat: "org.apache.hadoop.mapred.TextInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe"
        TableType: "EXTERNAL_TABLE"